### ISSUE TITLE
有兴趣做react前端开发的实习/全职吗？

### ISSUE THREAD

**Issue by dr970427** [magezee/gegeda#1]
1.熟练使用 React Hooks 和 Typescript,能基于hook封装复用各种基础组件，并提供友好的ts定义；
2.熟练使用一种CSS预编译语法(less、sass) 或者 styled-components；
3.使用React Native 开发过跨平台APP；
4.熟悉CSS3，使用flex grid 等新技术实现H5/PC/小程序页面。

全职2w/月左右，实习根据面试情况而定，可200-500/天。

**Comment by Morgiana-V3** [comment]
no
